export * as DevicePreview from "./device-preview"

import { Schema } from "effect"
import { NonNegativeInt, optional } from "./schema"

export const Platform = Schema.Literals(["ios", "android"])
export type Platform = typeof Platform.Type

// How the app is built: an Expo app (native projects generated by prebuild), a bare React Native
// app (native projects checked in, JS served by Metro), or a plain native app.
export const Framework = Schema.Literals(["expo", "react-native", "native"])
export type Framework = typeof Framework.Type

export const Status = Schema.Literals(["starting", "running", "exited"])
export type Status = typeof Status.Type

export interface Server extends Schema.Schema.Type<typeof Server> {}
export const Server = Schema.Struct({
  platform: Platform,
  status: Status,
  // Human-readable command line, e.g. `npx --yes serve-sim`.
  command: Schema.String,
  // Preview UI origin once the tool reports it, e.g. `http://localhost:3200`.
  url: optional(Schema.String),
  pid: optional(NonNegativeInt),
  exitCode: optional(Schema.Int),
  // Most recent lines of combined stdout/stderr with ANSI escapes removed.
  log: Schema.Array(Schema.String),
}).annotate({ identifier: "DevicePreview.Server" })

export interface Bundler extends Schema.Schema.Type<typeof Bundler> {}
export const Bundler = Schema.Struct({
  framework: Framework,
  // JavaScript project root the bundler serves, shared by the iOS and Android apps.
  directory: Schema.String,
  status: Status,
  // Human-readable command line, e.g. `npx expo start --dev-client`.
  command: Schema.String,
  // Metro origin once it answers, e.g. `http://localhost:8081`.
  url: optional(Schema.String),
  pid: optional(NonNegativeInt),
  exitCode: optional(Schema.Int),
  log: Schema.Array(Schema.String),
}).annotate({ identifier: "DevicePreview.Bundler" })

export const BuildStatus = Schema.Literals(["idle", "building", "installing", "launching", "running", "failed"])
export type BuildStatus = typeof BuildStatus.Type

export interface Build extends Schema.Schema.Type<typeof Build> {}
export const Build = Schema.Struct({
  platform: Platform,
  framework: optional(Framework),
  status: BuildStatus,
  // Native project directory this build targets, which may be below the session directory.
  directory: optional(Schema.String),
  // Xcode scheme or Gradle module.
  target: optional(Schema.String),
  // Bundle identifier or Android package name.
  appID: optional(Schema.String),
  // Short description of the current step, shown next to the run control.
  step: optional(Schema.String),
  error: optional(Schema.String),
  log: Schema.Array(Schema.String),
  startedAt: optional(NonNegativeInt),
  finishedAt: optional(NonNegativeInt),
}).annotate({ identifier: "DevicePreview.Build" })

export interface Info extends Schema.Schema.Type<typeof Info> {}
export const Info = Schema.Struct({
  // Platforms detected from the project files at or below the requested location.
  platforms: Schema.Array(Platform),
  // Framework of the detected project, when any platform was found.
  framework: optional(Framework),
  // Metro bundler for the detected React Native or Expo project, once started.
  bundler: optional(Bundler),
  // Preview servers managed by this opencode process, regardless of location.
  servers: Schema.Array(Server),
  // Build and run state for the requested location.
  builds: Schema.Array(Build),
}).annotate({ identifier: "DevicePreview.Info" })

export interface PlatformInput extends Schema.Schema.Type<typeof PlatformInput> {}
export const PlatformInput = Schema.Struct({
  platform: Platform,
}).annotate({ identifier: "DevicePreview.PlatformInput" })

export interface RunInput extends Schema.Schema.Type<typeof RunInput> {}
export const RunInput = Schema.Struct({
  platform: Platform,
  // Launch the app already installed from the previous run when possible instead of rebuilding.
  relaunch: optional(Schema.Boolean),
}).annotate({ identifier: "DevicePreview.RunInput" })
